# Generated by Django 2.2.4 on 2019-09-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('r_time', models.DateTimeField(auto_now=True)),
                ('r_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('r_person', models.CharField(max_length=32)),
                ('p_id', models.IntegerField(max_length=32)),
            ],
        ),
    ]
